### ISSUE TITLE
Rust testing

### ISSUE THREAD

**Issue by ayourk** [MiniMage7/Match3Solver#10]
I'm using Ubuntu Linux and the stock Rust packages that come with 22.04.  After building without errors, I run the executable and get:

```
ayourk@Z590-P:..3/rust2/rust-match-3-solver>RUST_BACKTRACE=full ./target/debug/rust-match-3-solver
Paste your exported board here:
(You can get your board by drawing it on the website and clicking the export button)
> { "height": 2, "width": 3, "board": [[1,2,1], [2,1,2]] }
How mant layers of threads do you want to spawn?
2 is recommended for most solves. 1 might be necessary for the larger solves. Larger numbers are faster but more intensive.
> 2
thread 'main' panicked at src/main.rs:49:86:
That is not a valid number.
stack backtrace:
   0:     0x55dd87364ec8 - std::backtrace_rs::backtrace::libunwind::trace::h0479db65bbf645ab
                               at /build/rustc-QLyM7K/rustc-1.74.1+dfsg0ubuntu1~bpo0/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55dd87364ec8 - std::backtrace_rs::backtrace::trace_unsynchronized::h86e3a8a7c40f1784
                               at /build/rustc-QLyM7K/rustc-1.74.1+dfsg0ubuntu1~bpo0/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55dd87364ec8 - std::sys_common::backtrace::_print_fmt::h92211022f37b5644
                               at /build/rustc-QLyM7K/rustc-1.74.1+dfsg0ubuntu1~bpo0/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55dd87364ec8 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h58a47dbc20dd410d
                               at /build/rustc-QLyM7K/rustc-1.74.1+dfsg0ubuntu1~bpo0/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55dd8738d08c - core::fmt::rt::Argument::fmt::h6a78f275a0911b63
                               at /build/rustc-QLyM7K/rustc-1.74.1+dfsg0ubuntu1~bpo0/library/core/src/fmt/rt.rs:138:9
   5:     0x55dd8738d08c - core::fmt::write::he356c44b2a0b68ef
                               at /build/rustc-QLyM7K/rustc-1.74.1+dfsg0ubuntu1~bpo0/library/core/src/fmt/mod.rs:1114:21
   6:     0x55dd87367c9d - std::io::Write::write_fmt::h86086e02f48aa1c0
                               at /build/rustc-QLyM7K/rustc-1.74.1+dfsg0ubuntu1~bpo0/library/std/src/io/mod.rs:1763:15
   7:     0x55dd87364c54 - std::sys_common::backtrace::_print::hef216654cf179e8d
                               at /build/rustc-QLyM7K/rustc-1.74.1+dfsg0ubuntu1~bpo0/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x55dd87364c54 - std::sys_common::backtrace::print::h4e55f3325563342f
                               at /build/rustc-QLyM7K/rustc-1.74.1+dfsg0ubuntu1~bpo0/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x55dd87375d13 - std::panicking::default_hook::{{closure}}::hce24a41e0fe9713f
                               at /build/rustc-QLyM7K/rustc-1.74.1+dfsg0ubuntu1~bpo0/library/std/src/panicking.rs:272:22
  10:     0x55dd87375a19 - std::panicking::default_hook::hf1799fd0d3dd1348
                               at /build/rustc-QLyM7K/rustc-1.74.1+dfsg0ubuntu1~bpo0/library/std/src/panicking.rs:292:9
  11:     0x55dd873761a5 - std::panicking::rust_panic_with_hook::h481ee4eb034adec0
                               at /build/rustc-QLyM7K/rustc-1.74.1+dfsg0ubuntu1~bpo0/library/std/src/panicking.rs:731:13
  12:     0x55dd87365506 - std::panicking::begin_panic_handler::{{closure}}::h556ae8745374dac3
                               at /build/rustc-QLyM7K/rustc-1.74.1+dfsg0ubuntu1~bpo0/library/std/src/panicking.rs:601:13
  13:     0x55dd87365356 - std::sys_common::backtrace::__rust_end_short_backtrace::h5f8005ee7ed611a4
                               at /build/rustc-QLyM7K/rustc-1.74.1+dfsg0ubuntu1~bpo0/library/std/src/sys_common/backtrace.rs:170:18
  14:     0x55dd87375ee2 - rust_begin_unwind
                               at /build/rustc-QLyM7K/rustc-1.74.1+dfsg0ubuntu1~bpo0/library/std/src/panicking.rs:597:5
  15:     0x55dd8730eb75 - core::panicking::panic_fmt::hf58b84fe45e631d5
                               at /build/rustc-QLyM7K/rustc-1.74.1+dfsg0ubuntu1~bpo0/library/core/src/panicking.rs:72:14
  16:     0x55dd8732600b - rust_match_3_solver::main::{{closure}}::h5e0fc792c6a817b2
                               at /var/www/html/match3/rust2/rust-match-3-solver/src/main.rs:49:86
  17:     0x55dd8732371c - core::result::Result<T,E>::unwrap_or_else::hf3567c582afe7873
                               at /build/rustc-QLyM7K/rustc-1.74.1+dfsg0ubuntu1~bpo0/library/core/src/result.rs:1429:23
  18:     0x55dd8731c2cb - rust_match_3_solver::main::hdb86734a91f106a3
                               at /var/www/html/match3/rust2/rust-match-3-solver/src/main.rs:49:28
  19:     0x55dd873351db - core::ops::function::FnOnce::call_once::h28aea1c47325406b
                               at /build/rustc-QLyM7K/rustc-1.74.1+dfsg0ubuntu1~bpo0/library/core/src/ops/function.rs:250:5
  20:     0x55dd87316d5e - std::sys_common::backtrace::__rust_begin_short_backtrace::h22f602702618959a
                               at /build/rustc-QLyM7K/rustc-1.74.1+dfsg0ubuntu1~bpo0/library/std/src/sys_common/backtrace.rs:154:18
  21:     0x55dd8732a361 - std::rt::lang_start::{{closure}}::h3ac8af5a4c016eec
                               at /build/rustc-QLyM7K/rustc-1.74.1+dfsg0ubuntu1~bpo0/library/std/src/rt.rs:166:18
  22:     0x55dd87368e77 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::he5fd7ff4ccf2cf44
                               at /build/rustc-QLyM7K/rustc-1.74.1+dfsg0ubuntu1~bpo0/library/core/src/ops/function.rs:284:13
  23:     0x55dd87368e77 - std::panicking::try::do_call::he1edb2fc6049b849
                               at /build/rustc-QLyM7K/rustc-1.74.1+dfsg0ubuntu1~bpo0/library/std/src/panicking.rs:504:40
  24:     0x55dd87368e77 - std::panicking::try::hb48578cfaa80f796
                               at /build/rustc-QLyM7K/rustc-1.74.1+dfsg0ubuntu1~bpo0/library/std/src/panicking.rs:468:19
  25:     0x55dd87368e77 - std::panic::catch_unwind::ha1231ca0a4e84020
                               at /build/rustc-QLyM7K/rustc-1.74.1+dfsg0ubuntu1~bpo0/library/std/src/panic.rs:142:14
  26:     0x55dd87368e77 - std::rt::lang_start_internal::{{closure}}::h51f7e9ba2ac2d93a
                               at /build/rustc-QLyM7K/rustc-1.74.1+dfsg0ubuntu1~bpo0/library/std/src/rt.rs:148:48
  27:     0x55dd87368e77 - std::panicking::try::do_call::hfaea7848529c4f58
                               at /build/rustc-QLyM7K/rustc-1.74.1+dfsg0ubuntu1~bpo0/library/std/src/panicking.rs:504:40
  28:     0x55dd87368e77 - std::panicking::try::h2c8b3ed041ada40f
                               at /build/rustc-QLyM7K/rustc-1.74.1+dfsg0ubuntu1~bpo0/library/std/src/panicking.rs:468:19
  29:     0x55dd87368e77 - std::panic::catch_unwind::h3c4cb3409fc40ad3
                               at /build/rustc-QLyM7K/rustc-1.74.1+dfsg0ubuntu1~bpo0/library/std/src/panic.rs:142:14
  30:     0x55dd87368e77 - std::rt::lang_start_internal::h9ae9c12dedb67f8b
                               at /build/rustc-QLyM7K/rustc-1.74.1+dfsg0ubuntu1~bpo0/library/std/src/rt.rs:148:20
  31:     0x55dd8732a33a - std::rt::lang_start::hbd7d928f0dec77f4
                               at /build/rustc-QLyM7K/rustc-1.74.1+dfsg0ubuntu1~bpo0/library/std/src/rt.rs:165:17
  32:     0x55dd8732098e - main
  33:     0x14a396829d90 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  34:     0x14a396829e40 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:392:3
  35:     0x55dd8730f325 - _start
  36:                0x0 - <unknown>
```

**Comment by MiniMage7** [comment]
Sorry that was an oversite on my part. It should be fixed now.

**Comment by ayourk** [comment]
Thanks.  Trying some larger solves and getting lots of errors too.  I'm working on capturing the logs.

**Comment by MiniMage7** [comment]
There is no max number of threads. However, on my system at least, running any of these will immediately cap all of my CPU resources. And depending on how your OS handles threads, there's a high chance that if you set it too high, you OS will not let the program spawn more.

**Comment by MiniMage7** [comment]
I've personally never had an issue with it on any puzzle as long as I set it to 1, but when I uncap it (like setting it to 10 or something), I have had my operating system crash the program on the very large puzzles.
